version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app   
    ports:
      - "8000:8000"  # ポートの指定形式を統一
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=calender
      - POSTGRES_USER=muent
      - POSTGRES_PASSWORD=calender
    ports:
      - "5432:5432"

volumes:
  postgres_data:
